title: Eone_homepage
description: A homepage.
author: XiuYi Chen
avatar: /persion_eone_log.png
email: Eoneanyna@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
sink: sunset
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: persion_eone_log.png
social:
  name: XiuYi Chen
  links:
    - https://github.com/Eoneanyna
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
